version: '3.8'
services:
  mariadb:
    image: mariadb
    container_name: mydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: videojuegos
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - 33066:3306
    volumes:
      - ./datos:/var/lib/mysql
    command: --bind-address=0.0.0.0

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: admin
      PMA_PASSWORD: root
    depends_on:
      - mariadb

      
      
      
