version: '3.8'
services:
  java_db:
    container_name: java_db
    image: postgres:13
    ports:
      - 5678:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: videojuegos
    volumes:
      - ./src/main/resources/schema-postgres.sql:/docker-entrypoint-initdb.d/data.sql
      - ./db-data:/var/lib/postgresql/data